services:
  - type: web
    name: trustshield-blockchain
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8545
      - key: HOST
        value: 0.0.0.0 