version: "3.9"
services:
  api:
    build: .
    command: python -m api.server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PORT=8000
      - DEBUG=true
      - PYTHONPATH=/app
    restart: unless-stopped
    
  ui:
    build: .
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
    restart: unless-stopped 